//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.10 at 12:02:28 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://exemplo.com/wsdlservidor/assets", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.examplo.wsdlservidor.assets;
